apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "robinmaniaserver"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7777
  template:
    spec:
      containers:
      - name: robinmaniaserver
        image: ziedchekir/robin_server:1.0
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
